### ISSUE TITLE
Support external libs

### ISSUE THREAD

**Issue by tseemann** [webmasterar/edso#1]
You seem to be hard coding vcflib and htslib.

Please support already installed versions, with `VCFLIB` and `HTSLIB` perhaps in your `Makefile` ?

**Comment by webmasterar** [comment]
Hello Torsten,

I'm not really sure how to do that. Could you please show me?

**Comment by tseemann** [comment]
I don't have time to go into detail but at the moment you have stuff like:
```
LFLAGS = -L./path/to/my/one -lhtslib
```
But you should break it up like
```
HTSLIB = ./path/to/my/htslib
LFLAGS = -L $(HTSLIB) -lhts
```
That way it works as you desire for `make`, but other people can type `make HTSLIB=/usr/local/lib` instead to use their local copy.

It's not critical - I don't need it anymore.
