### ISSUE TITLE
Running out of memory with human genome data

### ISSUE THREAD

**Issue by urbanslug** [webmasterar/edso#2]
According to [sopang](https://github.com/MrAlexSee/sopang) this tool has been used to generate EDS files from human genome data. I however tried generating eds files from human genome data chromosome 1
 - [fasta](https://ftp.ensembl.org/pub/release-105/fasta/homo_sapiens/dna/)
 - [vcf](https://ftp.ensembl.org/pub/release-105/variation/vcf/homo_sapiens/)
 
Downloaded:
```
https://ftp.ensembl.org/pub/release-105/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.1.fa.gz
https://ftp.ensembl.org/pub/release-105/variation/vcf/homo_sapiens/homo_sapiens-chr1.vcf.gz
```
 
 but ran out of memory even on a server with over 100G of RAM with
 ```
  edso Homo_sapiens.GRCh38.dna.chromosome.1.fa homo_sapiens-chr1.vcf.gz homo_sapiens-ch1.eds
 ```
 
 Could there be something I'm doing wrong?

**Comment by webmasterar** [comment]
Hello.

There is a problem with the implementation in the code. This project is no longer maintained so unfortunately I do not have the time to fix it. What you can do is switch to commit c7841ecd29 and from my tests, that version will not run out of memory. The difference between that and the current version is how it handles nested variants, which is faulty and is using up all the memory in the current version. As an alternative, you can comment out lines 112-131 of main.cpp in the current version to the same effect.

Apologies for the inconvenience.

Ahmad

**Comment by urbanslug** [comment]
Thanks
